# Generated by Django 3.2.10 on 2022-01-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(db_column='user_email', max_length=254, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'cliente'), ('MANAGER', 'administrador')], db_column='user_type', default='CLIENT', max_length=15, null=True, verbose_name='tipo de usuario'),
        ),
    ]
