# Generated by Django 3.2.10 on 2022-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'cliente'), ('MANAGER', 'administrador')], db_column='user_type', default='CLIENT', max_length=15, null=True, verbose_name='tipo de usuario'),
        ),
    ]
