# Generated by Django 3.2.10 on 2022-01-06 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('user_lastname', models.CharField(max_length=30, verbose_name='apellidos')),
                ('user_birthday', models.DateTimeField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('user_phone', models.CharField(max_length=10, null=True, verbose_name='telefono/celular')),
                ('user_address', models.CharField(max_length=64, null=True, verbose_name='dirección')),
                ('user_occupation', models.CharField(max_length=64, null=True, verbose_name='ocupación')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='perfil de usuario')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
