# Generated by Django 3.2.10 on 2022-02-25 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='user_name', max_length=30, verbose_name='nombre')),
                ('lastname', models.CharField(db_column='user_lastname', max_length=30, verbose_name='apellidos')),
                ('age', models.PositiveSmallIntegerField(blank=True, db_column='user_age', null=True, verbose_name='Edad')),
                ('phone', models.CharField(blank=True, db_column='user_phone', max_length=10, null=True, verbose_name='teléfono/celular')),
                ('address', models.CharField(blank=True, db_column='user_address', max_length=64, null=True, verbose_name='dirección')),
                ('occupation', models.CharField(blank=True, db_column='user_occupation', max_length=64, null=True, verbose_name='ocupación')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='perfil de usuario')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-create_at'],
            },
        ),
    ]
