# Generated by Django 3.2.10 on 2022-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_occupation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ocupación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='telefono/celular'),
        ),
    ]
