# Generated by Django 3.2.10 on 2022-01-15 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_alter_order_user'),
        ('notifications', '0002_initial'),
        ('users', '0003_alter_user_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
