# Generated by Django 3.2.10 on 2022-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('user_lastname', models.CharField(max_length=30, verbose_name='apellidos')),
                ('user_birthday', models.DateTimeField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('user_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='teléfono/celular')),
                ('user_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='dirección')),
                ('user_occupation', models.CharField(blank=True, max_length=64, null=True, verbose_name='ocupación')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_profile',
        ),
    ]
