# Generated by Django 3.2.10 on 2022-01-18 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220118_1518'),
        ('notifications', '0003_alter_notification_user'),
        ('orders', '0003_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='perfil de usuario'),
        ),
    ]
