# Generated by Django 3.2.10 on 2022-01-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220118_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, db_column='user_age', null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, db_column='user_address', max_length=64, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(db_column='user_lastname', max_length=30, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='user_name', max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, db_column='user_occupation', max_length=64, null=True, verbose_name='ocupación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_column='user_phone', max_length=10, null=True, verbose_name='teléfono/celular'),
        ),
    ]
