# Generated by Django 3.2.10 on 2022-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, db_column='user_age', null=True, verbose_name='Edad'),
        ),
    ]
