# Generated by Django 3.2.10 on 2022-02-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='cat_name', max_length=64, verbose_name='nombre')),
                ('description', models.CharField(blank=True, db_column='cat_description', max_length=254, null=True, verbose_name='descripcion')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-name'],
            },
        ),
    ]
