# Generated by Django 3.2.10 on 2022-01-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220128_1731'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='categorias', to='products.Product', verbose_name='productos'),
        ),
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
    ]
