# Generated by Django 3.2.10 on 2022-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_reference'),
        ('categories', '0006_alter_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='categories', to='products.Product', verbose_name='productos'),
        ),
    ]
