# Generated by Django 3.2.10 on 2022-02-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
