# Generated by Django 3.2.10 on 2022-02-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CONFIRMED', 'confirmado'), ('UNCONFIRMED', 'confirmado'), ('CANCELLED', 'cancelado'), ('DISPATCHED', 'despachado'), ('DELIVERED', 'entregado')], db_column='ord_state', max_length=15, verbose_name='estado')),
                ('total', models.PositiveSmallIntegerField(db_column='ord_total', verbose_name='total')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='ord_date', verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='cantidad')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='pedido')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'producto/pedido',
                'verbose_name_plural': 'productos/pedidos',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProduct', to='products.Product'),
        ),
    ]
