# Generated by Django 3.2.10 on 2022-01-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220128_1731'),
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ord_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ord_total',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CONFIRMED', 'confirmado'), ('UNCONFIRMED', 'confirmado'), ('CANCELLED', 'cancelado'), ('DISPATCHED', 'despachado'), ('DELIVERED', 'entregado')], db_column='ord_state', max_length=15, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(db_column='ord_total', verbose_name='total'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='pedido')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'producto/pedido',
                'verbose_name_plural': 'productos/pedidos',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProduct', to='products.Product'),
        ),
    ]
