# Generated by Django 3.2.10 on 2022-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220129_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveSmallIntegerField(db_column='ord_total', verbose_name='total'),
        ),
    ]
