# Generated by Django 3.2.10 on 2022-01-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('not_title', models.CharField(blank=True, max_length=25, null=True, verbose_name='titulo')),
                ('not_body', models.CharField(blank=True, max_length=254, null=True, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
            },
        ),
    ]
