# Generated by Django 3.2.10 on 2022-02-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='noti_date')),
                ('title', models.CharField(db_column='noti_title', default='Notification', max_length=25, verbose_name='titulo')),
                ('body', models.CharField(blank=True, db_column='noti_body', max_length=254, null=True, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-date'],
            },
        ),
    ]
