# Generated by Django 3.2.10 on 2022-01-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='not_body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='not_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='not_title',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, db_column='noti_body', max_length=254, null=True, verbose_name='texto'),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='noti_date', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, db_column='noti_title', max_length=25, null=True, verbose_name='titulo'),
        ),
    ]
