# Generated by Django 3.2.10 on 2022-01-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20220128_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date'], 'verbose_name': 'notificacion', 'verbose_name_plural': 'notificaciones'},
        ),
    ]
