# Generated by Django 3.2.10 on 2022-02-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='prod_name', max_length=254, verbose_name='nombre')),
                ('amount', models.PositiveIntegerField(db_column='prod_amount', verbose_name='cantidad')),
                ('price', models.PositiveIntegerField(db_column='prod_price', verbose_name='precio')),
                ('description', models.CharField(blank=True, db_column='prod_description', max_length=254, verbose_name='descripción')),
                ('trademark', models.CharField(blank=True, db_column='prod_trademark', max_length=64, null=True, verbose_name='marca')),
                ('warranty', models.CharField(blank=True, db_column='prod_warranty', max_length=20, null=True, verbose_name='garantía')),
                ('tutorial_url', models.URLField(blank=True, db_column='prod_tutorial', null=True, verbose_name='link del tutorial')),
                ('discount', models.PositiveSmallIntegerField(blank=True, db_column='prod_discount', default=0, null=True, verbose_name='descuento')),
                ('reference', models.CharField(blank=True, db_column='prod_reference', default='sin referencia', max_length=64, verbose_name='referencia')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='categories.Category', verbose_name='categorias')),
            ],
            options={
                'verbose_name': 'productos',
                'verbose_name_plural': 'productos',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.ImageField(blank=True, db_column='prod_image', null=True, upload_to='media/products/', verbose_name='ruta de la imagen')),
                ('product', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagenes de producto',
                'verbose_name_plural': 'imagenes de productos',
                'ordering': ['product'],
            },
        ),
    ]
