# Generated by Django 3.2.10 on 2022-01-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=254, verbose_name='nombre')),
                ('prod_amount', models.IntegerField(verbose_name='cantidad')),
                ('prod_price', models.IntegerField(verbose_name='precio')),
                ('prod_description', models.CharField(blank=True, max_length=254, verbose_name='descripción')),
                ('prod_image_url', models.URLField(blank=True, null=True, verbose_name='ubicación')),
                ('prod_trademark', models.CharField(blank=True, max_length=64, null=True, verbose_name='marca')),
                ('prod_warranty', models.CharField(blank=True, max_length=20, null=True, verbose_name='garantía')),
                ('prod_tutorial_url', models.URLField(blank=True, null=True, verbose_name='link del tutorial')),
                ('prod_discount', models.IntegerField(verbose_name='descuento')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'productos',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', unique=True, verbose_name='id del pedido')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True, verbose_name='id del producto')),
            ],
            options={
                'verbose_name': 'producto/pedido',
                'verbose_name_plural': 'productos/pedidos',
            },
        ),
    ]
