# Generated by Django 3.2.10 on 2022-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='descuento'),
        ),
    ]
