# Generated by Django 3.2.10 on 2022-02-26 02:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='path_image',
            field=cloudinary.models.CloudinaryField(db_column='prod_image', default='aldof', max_length=255, verbose_name='ruta de la imagen'),
            preserve_default=False,
        ),
    ]
