# Generated by Django 3.2.10 on 2022-01-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user'),
        ('products', '0002_auto_20220107_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='producto'),
        ),
    ]
