# Generated by Django 3.2.10 on 2022-02-26 02:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_path_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='path_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
