# Generated by Django 3.2.10 on 2022-01-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_prod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_trademark',
            new_name='trademark',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_warranty',
            new_name='warranty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_tutorial_url',
        ),
        migrations.AddField(
            model_name='product',
            name='tutorial_url',
            field=models.URLField(blank=True, db_column='prod_tutorial', null=True, verbose_name='link del tutorial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(db_column='prod_amount', verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_column='prod_description', max_length=254, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, db_column='prod_discount', default=0, null=True, verbose_name='descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, db_column='prod_image', null=True, upload_to='media/products/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='prod_name', max_length=254, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_column='prod_price', verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trademark',
            field=models.CharField(blank=True, db_column='prod_trademark', max_length=64, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, db_column='prod_warranty', max_length=20, null=True, verbose_name='garantía'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
