# Generated by Django 3.2.10 on 2022-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220129_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(db_column='prod_reference', default='sin referencia', max_length=64, verbose_name='referencia'),
        ),
    ]
