# Generated by Django 3.2.10 on 2022-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_remove_category_products'),
        ('products', '0008_product_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='categories.Category', verbose_name='categorias'),
        ),
    ]
