# Generated by Django 3.2.10 on 2022-02-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, db_column='prod_reference', default='sin referencia', max_length=64, verbose_name='referencia'),
        ),
    ]
